FROM node:22 AS build
WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Pass domain into build
ARG VITE_APP_DOMAIN
ENV VITE_APP_DOMAIN=${VITE_APP_DOMAIN}

RUN pnpm run build

# -------------------------------
# Production Stage (Nginx)
# -------------------------------

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
