FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /LibraryManagementAPI

COPY *.csproj ./

RUN dotnet restore

COPY . ./


RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /out .

EXPOSE 5049

ENV ASPNETCORE_URLS=http://+:5049

ENTRYPOINT [ "dotnet", "LibraryManagementAPI.dll" ]